### ISSUE TITLE
AttributeError when trying to delete objects

### ISSUE THREAD

**Issue by malinastrand** [freand76/digsim#3]
When trying to delete an object (button, switch, etc) using right click->delete I get this error:
`Traceback (most recent call last):
  File "/home/malin/.local/lib/python3.10/site-packages/digsim/app/gui_objects/_component_context_menu.py", line 61, in _delete
    self._component_object.select(True)
AttributeError: 'ButtonObject' object has no attribute 'select'. Did you mean: 'selected'?
`
and the object is not deleted. 

Highlighting the object and pressing the trashcan icon works.

**Comment by freand76** [comment]
Thanks! Fixed in release v0.4.0
